### PR TITLE
Frontpage screening frontend

### PR DESCRIPTION
**Pull request by MickeMarten**
Made fetch from api and rendered inside class.
0 design.
Ignore the test-files. They will be overwritten in next PR. (Used the wrong branch).
Review frontPage.js.
I have a good eye for design.
Skärmklipp

### CODE REVIEW

**Review by AlbinNils98 — APPROVED** [review]
The frontend code looks really clean and it seems to be working properly. **Nice job!** One thing i would comment on is that the "seconds" in screening time is shown (17:00:00), that seems a bit unnecessary.

**Comment by MickeMarten** [comment]
I Will extend my slice-method. Thanks for the notice.

**Comment by MickeMarten** [comment]
All issues should be fixed.
Files deleted and seconds do not show on frontpage.

**Comment by MickeMarten** [comment]
Looks good when I merge local main and branch.

**Review by oskber — APPROVED** [review]
I agree, it looks good! Maybe you could change font color to white, so it's easier to see.

**Pull request merged**
