### PR TITLE
Reviews test

### PR DESCRIPTION
**Pull request by AlbinNils98**
Created a CMS adapter to be used by all collaborators and included that in my existing code so i had to make some minor changes. 

Made a test that checks if an array that goes through getReviewsSizeFive gets paginated to size of 5 and only returns verified reviews and reviews that have a rating between 0 and 5.

### CODE REVIEW

**Review by oskber — APPROVED** [review]
Nice, looks good to me. Will try to use it.

**Comment by MickeMarten** [comment]
Good job adepting the cms-adapter to your test. From my point of view it wasn't easy. Would love a genomgång.

**Review by MadeleineDahlqvist — APPROVED** [review]
Looks good, great job! Agree with Micke, a "genomgång" sounds nice :)

**Review by maxlin94 — APPROVED** [review]
Looks good, nice work!

**Review by MickeMarten — APPROVED** [review]
I found the button :)

**Pull request merged**
