### PR TITLE
Added styling

### PR DESCRIPTION
**Pull request by AlbinNils98**
Added styling to frontpage screenings list. Also made it so ratings are centered under movies

### CODE REVIEW

**Comment by MickeMarten** [comment]
Lets go!

**Review by MickeMarten — COMMENTED** [review]
Let's go!

**Review by MickeMarten — COMMENTED** [review]
Can't seem to find the Review changes button.

**Review by MickeMarten — APPROVED** [review]
Shit..

**Review by ConnyPettersson — APPROVED** [review]
Looks good!

**Pull request merged**
